version: '3.8'

services:
  db:
    image: postgres:17
    container_name: fatec-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: papinha123
    ports:
      - "5432:5432"
    networks:
      - fatec-network
  app:
    container_name: fatec-api-container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db 
    environment:
      PORT: 3000
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: f@tec
      API_KEY: agoravai123
      JWT_SECRET: jafoi15
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: papinha123
      DATABASE_NAME: cascata
    networks:
      - fatec-network

networks:
  fatec-network:
    driver: bridge